[build]
  command = "php index.php" # Comando para executar o arquivo index.php

[[redirects]]
  from = "/*.php" # Redirecionar todas as solicitações de arquivos .php para o processa.php
  to = "/processa.php"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
